### ISSUE TITLE
Some applications becomes very blurred during move and resizing.

### ISSUE THREAD

**Issue by tnilzon** [Noobsai/transparent-window-moving#1]
Some applications becomes very blurred during move and resizing. Try these for example: GIMP, Gpick, KeepassXC, Audacity, Spotify and many more. Other windows appears as they should (not blurred) during move/resize.

Perhaps the extension needs an update to gnome v3.34?

Transparent Window Moving (installed from this page)
OS: Manjaro gnome v3.34.1

**Comment by Noobsai** [comment]
Thank you for reporting!
Unfortunately I can't fix that because it's a [mutter bug](https://gitlab.gnome.org/GNOME/mutter/issues/836).

**Comment by tnilzon** [comment]
OK, lets hope for a fix then.
(I cal also now add Thunderbird to the list of bad examples...)

:-(

**Comment by tnilzon** [comment]
OK, thanks. Lets hope for a fix soon then!
(I can now also add Thunderbird to the affected applications).
:-(
