### ISSUE TITLE
Not working on gnome 43 (mutter > 43.0)

### ISSUE THREAD

**Issue by foer** [Noobsai/transparent-window-moving#15]
The extension stops working after updating mutter to 43.1, with is the most recent Version. With mutter 43.0 there were no issues.

**Comment by Noobsai** [comment]
Any logs?

**Comment by foer** [comment]
> Any logs?

There are no errors in looking glass. Where else can i find log files?

Some more informations:

To clarify: there are no errors while activating and running the extension. But dragging a window and moving it around leads to a "ghosting" effect. Numbers, letters and buttons follows as a shadow. The windows background is solid and not transparent. Sadly it's not visible on a screencast.

I am using manjaro with gnome shell 43.1 and mutter 43.1 in a wayland session.

**Comment by sonicnkt** [comment]
Weird, i am also running manjaro and just updated a few ours ago.
I also noticed an issue with this extension but something completely different.

I tloads fine but the transparency is only shown in a small squares of every corner of the window. The rest is completely opaque but seems a bit blurred.
I cant take a screenshot of this but i created this mockup which shows what it looks like:

![image](https://user-images.githubusercontent.com/5454622/201724933-fa3fc1e4-87d2-4b57-a141-b4cb44c939fb.png)

**Comment by tehbuhtig** [comment]
I am having problems similar to what foer described above. Fully updated EndeavourOS using wayland. Oddly enough, gnome-terminal seems to work just fine, while most others (firefox, nautilus) exhibit the blurry + ghosting behavior. 

Let me know if I can do anything else to help.

**Comment by Noobsai** [comment]
Hi all! Unfortunately cannot test on wayland right now, but X11 works fine. So it is highly likely an upstream bug (mutter or gnome-shell)

**Comment by foer** [comment]
One remark: I've tested the extension on x11 an can confirm that it's working there

**Comment by Noobsai** [comment]
Hi all. Fixed in [v12](https://github.com/Noobsai/transparent-window-moving/releases/tag/v12)!

I found device with the wayland on 43.1. It wasn't a mutter bug, they just added one more level for wayland window compositor: `MetaSurfaceContainerActor`. This breaks my extension, I didn't expect that changes. Now the algorithm is more stable

**Comment by foer** [comment]
Can confirm that the fix is working! Thank you very much!

**Comment by tehbuhtig** [comment]
Another confirmation that the update fixed the issue, and another huge thanks!
