### ISSUE TITLE
Transparency not applied when resizing with secondary-click and window action key

### ISSUE THREAD

**Issue by weskoerber** [Noobsai/transparent-window-moving#17]
Transparency is properly applied when resizing windows the "normal" way -- i.e. left-click-and-drag at the edge of a window. However, when using the window action key (Super in my case) and right-click-and-drag the transparency is not applied.

System info:
- Arch Linux
- GNOME Shell 44.1
- Wayland

**Comment by Noobsai** [comment]
gnome shell version? 
system name?
wayland or x11?

**Comment by weskoerber** [comment]
> gnome shell version? system name? wayland or x11?

My apologies for the lack of info in the initial report. I've updated my issue.

**Comment by zelch** [comment]
Same deal for moving windows using a modifier key and clicking somewhere on the window to drag it around.

No transparency effect in that case.

**Comment by Noobsai** [comment]
@zelch, I fixed this for gnome-shell 45. 
I'm not sure I'll update older versions, maybe later. 
Anyway you can fix this by editing the `extension.js`, see commit ee9de1e86d0ce9b749f3418c55197c9bc89e7f38

**Comment by ProjectInfinity** [comment]
@Noobsai Issue is back for GNOME 46.
