### ISSUE TITLE
GNOME 47 support

### ISSUE THREAD

**Issue by theDrake** [Noobsai/transparent-window-moving#24]
When possible, please update this wonderful extension for GNOME Shell v47. Thank you!

**Comment by theDrake** [comment]
The extension still doesn't work under GNOME Shell v47:
![image](https://github.com/user-attachments/assets/1ddaa4ed-9ba1-4bc9-8f6b-a1c8ee6bf1fe)

**Comment by Noobsai** [comment]
This file has been [deprecated](https://gjs.guide/extensions/upgrading/gnome-shell-44.html#gsettings-schema) since gnome-shell 44. It's weird, gnome-shell 47 wanted it again.
