### ISSUE TITLE
Feature Request : blur-my-shell integration

### ISSUE THREAD

**Issue by ryanfelder** [Noobsai/transparent-window-moving#26]
I use blur-my-shell, however when I also use transparent-window-moving, the blur seems to be disabled upon moving a window.

It would be very slick if somehow this extension and blur-my-shell worked better together, so that transparent windows did not lose their blur when being moved, and non-transparent windows would be blurred when made transparent by this extension.

**Comment by Noobsai** [comment]
I have tested it in various configurations and cannot confirm the issue. Could you record a video?

**Comment by ryanfelder** [comment]
I apologize, this was caused by a different extension, compiz window effects. 
When I disable it, transparent window moving works perfectly.
