### ISSUE TITLE
Extension not working on Gnome 40

### ISSUE THREAD

**Issue by fuelflo** [Noobsai/transparent-window-moving#5]
Hey,

unfortunately the extension does not work on Gnome 40. I get following error:

> TypeError: widget.show_all is not a function
> 
> Stack trace:
>   buildPrefsWidget@/home/flo/.local/share/gnome-shell/extensions/transparent-window-moving@noobsai.github.com/prefs.js:69:12
>   _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
>   OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
>   asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
>   run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
>   main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
>   run@resource:///org/gnome/gjs/modules/script/package.js:206:19
>   start@resource:///org/gnome/gjs/modules/script/package.js:190:8
>   @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

Is there anything that can be done to get it back running?

**Comment by Noobsai** [comment]
Do you have X11 or Wayland? I need some help testing.
Install the extension from the brunch: https://github.com/Noobsai/transparent-window-moving/tree/gnome-shell-40 
```
git clone https://github.com/Noobsai/transparent-window-moving.git
cd transparent-window-moving
git checkout gnome-shell-40
make install
```
(or just replace extension.js,  metadata.json, prefs.js from the git to extension folder)
After that restart a gnome-shell or log-out.
I tested it only on Wayland. I'd like to test on X11.
To check X11 or Wayland just run in command line: `echo $XDG_SESSION_TYPE`

**Comment by fuelflo** [comment]
Hey,

unfortunately I'm on Wayland too. But I can confirm it working there.

Only minor thing are border margins and stretched toggle buttons in the settings menu of the extension.
![Screenshot from 2021-04-11 16-16-00](https://user-images.githubusercontent.com/8934762/114307914-68ade000-9ad1-11eb-919b-ad543cdf22a7.png)
