### ISSUE TITLE
Firefox is not made transparent when the window is moved

### ISSUE THREAD

**Issue by redgryphon** [Noobsai/transparent-window-moving#7]
Easy as it is in the title: Firefox does not get transparent when moved, differently from the other windows.

**Comment by Noobsai** [comment]
Hi, I tried Firefox 88.0.1 on Arch linux with gnome-shell 40 and it works fine. What is your system?

**Comment by redgryphon** [comment]
My setup is the following:
Bare metal
Fedora 34
Mesa Intel P630
Wayland
Gnome 40.1.0
Default Adwaita theme
Firefox 88.0.1
